                                Getting familiarity with Numpy

In [7]:
import numpy as np

In [8]:
# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5,6,7,8,9])
print(arr1)

[1 2 3 4 5 6 7 8 9]


In [9]:
# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


                                      # Basic operations

In [11]:
array_sum=arr1+ 10
print(array_sum)

[11 12 13 14 15 16 17 18 19]


In [12]:
array_product=arr2* 5
print(array_product)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


                                     # array properties

In [20]:
print(arr2.shape)
print(arr2.dtype)
print(arr2.ndim)

(3, 3)
int64
2


                                     Data Manipulation

In [26]:
                                     # Create a 4x4 array
arr4 = np.arange(16).reshape(4, 4)
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
                                     # Indexing
element_value = arr[2, 1]
print(element_value)

7


In [31]:
                                     # Slicing
slice_array = arr[:2, 1:]
print(slice_array)

[[1 2]
 [4 5]]


In [37]:
                                  # Reshaping
reshaped_array = arr4.reshape(2, 8)
print(reshaped_array)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


                              Data Aggregation

In [38]:
mean_value = np.mean(arr4)
print(mean_value)

7.5


In [39]:
median_value = np.median(arr4)
print(median_value)

7.5


In [41]:
std_dev = np.std(arr4)
print(std_dev)

4.6097722286464435


In [46]:
sum_total = np.sum(arr4)
print(sum_total)

120


In [48]:
                            # Grouping
even_number = arr[arr % 2 == 0]
print(even_numbers)
odd_number = arr[arr % 2 != 0]
print(odd_numbers)

[0 2 4 6 8]
[1 3 5 7]


In [49]:
                             # Aggregation on groups
sum_even = np.sum(even_number)
print(sum_even)
sum_odd = np.sum(odd_number)
print(sum_odd)

20
16


                               Data Analysis

In [51]:
data_size = 1000
arr1 = np.random.uniform(1, 1000, data_size)
arr2 = np.random.uniform(1, 1000, data_size)

In [52]:
    # Calculate the correlation coefficient between arr1 and arr2
correlation_matrix = np.corrcoef(arr1, arr2)
correlation = correlation_matrix[0, 1]
print("Correlation Coefficient between arr1 and arr2:", correlation)

Correlation Coefficient between arr1 and arr2: -0.052123106335290006


In [59]:
data1 = np.array([1, 2, 3, 4, 100, 6, 7, 8, 9])
# Calculate the z-scores
z_scores = (data1 - np.mean(data1)) / np.std(data1)
print(z_scores)

[-0.4857185  -0.45234853 -0.41897856 -0.38560858  2.81790887 -0.31886864
 -0.28549866 -0.25212869 -0.21875871]


In [61]:
outliers = data1[np.abs(z_scores) > 2]
print(outliers)

[100]


In [64]:
                              # Calculate percentiles
percentile_90 = np.percentile(data1, 90)
print(percentile_90)

27.200000000000017


                                       Application in Data Science: 